[package]
name = "custom_adder"
version = "0.1.0"
edition = "2021"

[dependencies]
shaku = "0.6.1"

[dependencies.libadder]
version = "0.1.0"
path = "../libadder"
default-features = false
features = ["add_one", "add_two"]
