[package]
name = "libadder"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[features]
default = ["add_one", "add_two", "add_three"]
add_one = []
add_two = []
add_three = []

[dependencies]
shaku = "0.6.1"
